#ifndef _CONTROLER_MACROS_H
#define _CONTROLER_MACROS_H

#define DEVICES_COUNT		8
#define SENSORS_COUNT		6
#define DATA_FRAME_SIZE		5

#define SIGNAL_STOP			0
#define SIGNAL_START		1
#define SIGNAL_CONTROL		2
#define SIGNAL_SWITCH		3
#define SIGNAL_EVENTS		4
#define SIGNAL_DEVICES		5

#endif // _CONTROLER_MACROS_H
